service:
  name: yyt-lobby

plugins:
  - serverless-webpack
  - serverless-prune-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-2
  stage: ${env:STAGE}
  tracing:
    apiGateway: true
    lambda: true
  logs:
    restApi: true
  apiGateway:
    minimumCompressionSize: 1024
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    REDIS_HOST: ${env:REDIS_HOST}
    REDIS_PASSWORD: ${env:REDIS_PASSWORD}
    WS_ENDPOINT: ${env:WS_ENDPOINT}
    CALLBACK_URL_PREFIX: ${env:CALLBACK_URL_PREFIX}
    JWT_SECRET_KEY: ${env:JWT_SECRET_KEY}
    CONFIG_BUCKET: ${env:CONFIG_BUCKET}
    APPS_OBJECT_KEY: ${env:APPS_OBJECT_KEY}
    SLACK_WEBHOOK_URL: ${env:SLACK_WEBHOOK_URL}
    SLACK_CHANNEL: ${env:SLACK_CHANNEL}
    SLACK_LOG_LEVEL: ${env:SLACK_LOG_LEVEL, "warn"}
    CONSOLE_LOG_LEVEL: ${env:CONSOLE_LOG_LEVEL, "trace"}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource:
        - Fn::Join:
            - ":"
            - - "arn:aws:lambda"
              - Ref: "AWS::Region"
              - Ref: "AWS::AccountId"
              - "function"
              - "*"
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
      Resource:
        - "arn:aws:s3:::${env:CONFIG_BUCKET}/*"

custom:
  prune:
    automatic: true
    number: 7

package:
  individually: true

functions:
  # auth:
  #   handler: src/auth.handle
  #   timeout: 3
  #   memorySize: 256
  connect:
    handler: src/connect.handle
    timeout: 6
    memorySize: 256
    events:
      - websocket:
          route: $connect
          # authorizer:
          #   name: auth
          #   identitySource:
          #     - route.request.querystring.authorization
  disconnect:
    handler: src/disconnect.handle
    timeout: 3
    memorySize: 256
    events:
      - websocket:
          route: $disconnect
  message:
    handler: src/message.handle
    timeout: 12
    memorySize: 256
    events:
      - websocket:
          route: $default
  invoked:
    handler: src/invoked.handle
    timeout: 6
    memorySize: 256
    events:
      - http: PUT /invoked/{appId}/{gameId}
  tick:
    handler: src/tick.handle
    timeout: 30
    memorySize: 256
    events:
      - schedule: cron(* * * * ? *)
  clearAppsCache:
    handler: src/cache.doClearAppsCache
    timeout: 6
    memorySize: 256
    events:
      - http: DELETE /_cache/apps
